# Docker-compose configuration for production

version: '2.1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django.production
    container_name: instagramania_django
    restart: unless-stopped
    volumes:
      - "/var/lib/docker-nginx/files/instagramania/assets:/files/assets"
      - "/var/log/instagramania:/var/log/instagramania"
    # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
    #  work.
    entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
    command: gunicorn instagramania.wsgi:application --workers 2 --bind :80
    networks:
      - default
      - instagramania_nginx
      - instagramania_postgres
    depends_on:
      - redis
    external_links:
      - postgres-12:postgres

  node:
    build:
      context: .
      dockerfile: Dockerfile-node.production
    container_name: instagramania_node
    restart: unless-stopped
    command: yarn start
    volumes:
      - "/var/lib/docker-nginx/files/instagramania/app/assets:/files/assets"
      - "/var/log/instagramania:/var/log/instagramania"
    networks:
      - default
      - instagramania_nginx

  redis:
    image: redis:4.0.10-alpine
    restart: unless-stopped
    sysctls:
      # To allow maintaining TCP backlog setting that defaults to 511
      net.core.somaxconn: 512
    volumes:
      - "/var/lib/docker-instagramania/redis:/data"
    networks:
      - default

# NB: These networks must be created by ansible and contain the global nginx/postgres containers.
# Keep it in sync with ansible/roles/deploy/tasks/main.yml!
networks:
  default:
    external:
      name: instagramania_default
  instagramania_nginx:
    external: true
  instagramania_postgres:
    external: true
