# Generated by Django 3.1.5 on 2021-01-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0003_auto_20210104_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_comment', to='sentiment_api.comment'),
        ),
    ]
