# Generated by Django 3.1.5 on 2021-01-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0007_auto_20210104_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='sentiment_api.comment'),
        ),
    ]
