# Generated by Django 3.1.5 on 2021-01-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0009_auto_20210104_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_positive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
