# Generated by Django 3.1.5 on 2021-01-06 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0010_auto_20210105_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
