# Generated by Django 3.1.5 on 2021-01-06 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0012_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
