# Generated by Django 3.1.5 on 2021-01-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0014_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
